name: whatsappui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: ">=2.9.0 <3.5"
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: ^2.0.2
  emoji_picker_flutter: ^2.1.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.02

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
